version: '3.9'
services:
  app:
    build: .
    container_name: reis_back
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
    volumes:
      - .:/src/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - reis_network

  postgres:
    image: postgres:latest
    container_name: reis_postgres
    restart: always
    ports:
      - '5353:5432'
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - reis_network

volumes:
  pgdata:
    driver: local
  pgadmin_data:
    driver: local

networks:
  reis_network:
    driver: bridge