"""add soft delete

Revision ID: a8d6f50272a7
Revises: 3da47cc9da26
Create Date: 2025-06-04 20:51:32.036599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8d6f50272a7'
down_revision: Union[str, None] = '3da47cc9da26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Adiciona a coluna como nullable temporariamente
    op.add_column('task', sa.Column('is_inactive', sa.Boolean(), nullable=True))

    # 2. Define False para todos os registros existentes
    op.execute("UPDATE task SET is_inactive = FALSE")

    # 3. Altera a coluna para NOT NULL
    op.alter_column('task', 'is_inactive', nullable=False)



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'is_inactive')
    # ### end Alembic commands ###
